services:
  twamp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twamp-client
    hostname: twamp-client
    image: twamp-client:latest
    environment:
      - PROBE_SOURCE=${PROBE_SOURCE}
    volumes:
      - twamp-client:/config
    networks:
      twamp-client:
    restart: unless-stopped

networks:
  twamp-client:
    driver: bridge

volumes:
  twamp-client:
